name: kyuu_test
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  sliding_up_panel2: ^3.3.0+1
  json_annotation: ^4.8.1
  internet_connection_checker: ^1.0.0+1
  shimmer: ^3.0.0
  logger: ^2.0.2+1
  extended_nested_scroll_view: ^6.1.2
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.18.1
  collection: ^1.18.0
  url_launcher: ^6.2.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.4
  freezed: ^2.4.5
  riverpod_generator: ^2.3.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
